"""Initial migration

Revision ID: 09f61ef4c3df
Revises: 
Create Date: 2026-03-25 09:10:46.239527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09f61ef4c3df'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=True)
    op.create_table('registry_geographicalextent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('geometry', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_geographicalextent_id'), 'registry_geographicalextent', ['id'], unique=False)
    op.create_index(op.f('ix_registry_geographicalextent_name'), 'registry_geographicalextent', ['name'], unique=False)
    op.create_table('registry_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_policy_id'), 'registry_policy', ['id'], unique=False)
    op.create_index(op.f('ix_registry_policy_name'), 'registry_policy', ['name'], unique=False)
    op.create_table('registry_securitymechanism',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('protocol_id', sa.Integer(), nullable=True),
    sa.Column('created_on', sa.DateTime(), nullable=True),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registry_securitymechanism_id'), 'registry_securitymechanism', ['id'], unique=False)
    op.create_index(op.f('ix_registry_securitymechanism_name'), 'registry_securitymechanism', ['name'], unique=False)
    op.create_table('utilities_uploadedfile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file', sa.String(length=512), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilities_uploadedfile_id'), 'utilities_uploadedfile', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=30), nullable=True),
    sa.Column('user_type', sa.Enum('admin', 'operator', 'viewer', name='usertype'), nullable=False),
    sa.Column('user_level_auth', sa.Enum('level_1', 'level_2', 'level_3', name='userlevelauth'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('is_military', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('utilities_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_issued', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('publish', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('uploadfile_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['uploadfile_id'], ['utilities_uploadedfile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilities_document_id'), 'utilities_document', ['id'], unique=False)
    op.create_index(op.f('ix_utilities_document_title'), 'utilities_document', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_utilities_document_title'), table_name='utilities_document')
    op.drop_index(op.f('ix_utilities_document_id'), table_name='utilities_document')
    op.drop_table('utilities_document')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_utilities_uploadedfile_id'), table_name='utilities_uploadedfile')
    op.drop_table('utilities_uploadedfile')
    op.drop_index(op.f('ix_registry_securitymechanism_name'), table_name='registry_securitymechanism')
    op.drop_index(op.f('ix_registry_securitymechanism_id'), table_name='registry_securitymechanism')
    op.drop_table('registry_securitymechanism')
    op.drop_index(op.f('ix_registry_policy_name'), table_name='registry_policy')
    op.drop_index(op.f('ix_registry_policy_id'), table_name='registry_policy')
    op.drop_table('registry_policy')
    op.drop_index(op.f('ix_registry_geographicalextent_name'), table_name='registry_geographicalextent')
    op.drop_index(op.f('ix_registry_geographicalextent_id'), table_name='registry_geographicalextent')
    op.drop_table('registry_geographicalextent')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
