"""create_system_logs

Revision ID: 6e3136c05e33
Revises: 7435b95b43a8
Create Date: 2026-03-28 13:26:56.685635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6e3136c05e33'
down_revision: Union[str, None] = '7435b95b43a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'BULK_OPERATIONS', 'LOGIN_SUCCESS', 'LOGIN_FAILURE', 'LOGOUT', 'PASSWORD_CHANGE', 'PASSWORD_RESET', 'TOKEN_REFRESH', 'PERMISSION_DENIED', 'API_ERROR', 'VALIDATION_ERROR', 'RATE_LIMIT_EXCEEDED', 'FILE_UPLOAD', 'FILE_DOWNLOAD', 'EXPORT_DATA', 'IMPORT_DATA', 'SLOW_QUERY', 'HIGH_MEMORY_USAGE', 'API_RESPONSE_TIME', name='eventtype'), nullable=False),
    sa.Column('severity', sa.Enum('DEBUG', 'INFO', 'WARNING', 'ERROR', 'CRITICAL', name='logseverity'), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=254), nullable=True),
    sa.Column('user_ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('stack_trace', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_logs_event_type'), 'system_logs', ['event_type'], unique=False)
    op.create_index(op.f('ix_system_logs_id'), 'system_logs', ['id'], unique=False)
    op.create_index(op.f('ix_system_logs_timestamp'), 'system_logs', ['timestamp'], unique=False)
    op.create_index('ix_system_logs_timestamp_event_type', 'system_logs', ['timestamp', 'event_type'], unique=False)
    op.create_index(op.f('ix_system_logs_user_id'), 'system_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_logs_user_id'), table_name='system_logs')
    op.drop_index('ix_system_logs_timestamp_event_type', table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_timestamp'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_id'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_event_type'), table_name='system_logs')
    op.drop_table('system_logs')
    # ### end Alembic commands ###
