"""update user model fields v2

Revision ID: 7435b95b43a8
Revises: c4082fedec30
Create Date: 2026-03-27 11:15:51.515910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def create_enum_if_not_exists(name, values):
    values_str = ", ".join([f"'{v}'" for v in values])
    op.execute(sa.text(f"""
        DO $$ BEGIN
            CREATE TYPE {name} AS ENUM ({values_str});
        EXCEPTION
            WHEN duplicate_object THEN null;
        END $$;
    """))


# revision identifiers, used by Alembic.
revision: str = '7435b95b43a8'
down_revision: Union[str, None] = 'c4082fedec30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Criar enums explicitamente usando blocos DO para evitar erros de duplicidade
    create_enum_if_not_exists('servicestatus', ['EM_APROVACAO', 'ATIVO', 'INATIVO', 'SUSPENSO'])
    create_enum_if_not_exists('servicelifecycle', ['PROPOSTA', 'CANDIDATO', 'OPERACIONAL', 'LEGADO', 'RETIRADO'])
    create_enum_if_not_exists('servicetipo', ['REST', 'SOAP', 'FTP', 'AMHS', 'OUTRO'])
    create_enum_if_not_exists('servicepublishstatus', ['PUBLICADO', 'RASCUNHO', 'INATIVO'])
    create_enum_if_not_exists('organizationtipo', ['PROVEDOR', 'CONSUMIDOR', 'PARCEIRO', 'OUTRO'])
    create_enum_if_not_exists('organizationstatus', ['ATIVO', 'INATIVO', 'EM_APROVACAO'])
    create_enum_if_not_exists('usertype', ['admin', 'gestor', 'usuario'])
    create_enum_if_not_exists('userlevelauth', ['total', 'parcial', 'restrita'])

    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', postgresql.ENUM('EM_APROVACAO', 'ATIVO', 'INATIVO', 'SUSPENSO', name='servicestatus', create_type=False), nullable=True),
    sa.Column('life_cycle', postgresql.ENUM('PROPOSTA', 'CANDIDATO', 'OPERACIONAL', 'LEGADO', 'RETIRADO', name='servicelifecycle', create_type=False), nullable=True),
    sa.Column('tipo', postgresql.ENUM('REST', 'SOAP', 'FTP', 'AMHS', 'OUTRO', name='servicetipo', create_type=False), nullable=True),
    sa.Column('publish_status', postgresql.ENUM('PUBLICADO', 'RASCUNHO', 'INATIVO', name='servicepublishstatus', create_type=False), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    op.create_table('contact_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_points_email'), 'contact_points', ['email'], unique=False)
    op.create_index(op.f('ix_contact_points_id'), 'contact_points', ['id'], unique=False)
    op.create_index(op.f('ix_contact_points_name'), 'contact_points', ['name'], unique=False)
    op.add_column('organizations', sa.Column('acronym', sa.String(length=20), nullable=True))
    op.add_column('organizations', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=500), nullable=True))
    op.add_column('organizations', sa.Column('tipo', postgresql.ENUM('PROVEDOR', 'CONSUMIDOR', 'PARCEIRO', 'OUTRO', name='organizationtipo', create_type=False), nullable=True))
    op.add_column('organizations', sa.Column('status', postgresql.ENUM('ATIVO', 'INATIVO', 'EM_APROVACAO', name='organizationstatus', create_type=False), nullable=True))
    
    # Atualizar campos da tabela users
    op.add_column('users', sa.Column('nome', sa.String(length=200), nullable=True))
    op.execute("UPDATE users SET nome = COALESCE(first_name, '') || ' ' || COALESCE(last_name, '')")
    op.alter_column('users', 'nome', nullable=False)
    
    op.add_column('users', sa.Column('user_type', postgresql.ENUM('admin', 'gestor', 'usuario', name='usertype', create_type=False), nullable=False, server_default='usuario'))
    op.add_column('users', sa.Column('user_level_auth', postgresql.ENUM('total', 'parcial', 'restrita', name='userlevelauth', create_type=False), nullable=False, server_default='restrita'))
    
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    
    op.drop_column('users', 'user_level_auth')
    op.drop_column('users', 'user_type')
    op.drop_column('users', 'nome')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'tipo')
    op.drop_column('organizations', 'logo_url')
    op.drop_column('organizations', 'description')
    op.drop_column('organizations', 'acronym')
    
    # Remover enums explicitamente (ignorando se não existirem)
    op.execute(sa.text("DROP TYPE IF EXISTS userlevelauth"))
    op.execute(sa.text("DROP TYPE IF EXISTS usertype"))
    op.execute(sa.text("DROP TYPE IF EXISTS organizationstatus"))
    op.execute(sa.text("DROP TYPE IF EXISTS organizationtipo"))
    
    op.drop_index(op.f('ix_contact_points_name'), table_name='contact_points')
    op.drop_index(op.f('ix_contact_points_id'), table_name='contact_points')
    op.drop_index(op.f('ix_contact_points_email'), table_name='contact_points')
    op.drop_table('contact_points')
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    
    # Remover enums de serviços (ignorando se não existirem)
    op.execute(sa.text("DROP TYPE IF EXISTS servicepublishstatus"))
    op.execute(sa.text("DROP TYPE IF EXISTS servicetipo"))
    op.execute(sa.text("DROP TYPE IF EXISTS servicelifecycle"))
    op.execute(sa.text("DROP TYPE IF EXISTS servicestatus"))
    # ### end Alembic commands ###
