"""update_system_log_model

Revision ID: 797b4d05fc36
Revises: 6e3136c05e33
Create Date: 2026-03-28 13:36:33.901701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '797b4d05fc36'
down_revision: Union[str, None] = '6e3136c05e33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_system_logs_user_id_timestamp', 'system_logs', ['user_id', 'timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_system_logs_user_id_timestamp', table_name='system_logs')
    # ### end Alembic commands ###
