"""Add contact points

Revision ID: 7defb5a236a8
Revises: 09f61ef4c3df
Create Date: 2026-03-25 09:11:15.657877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7defb5a236a8'
down_revision: Union[str, None] = '09f61ef4c3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_points_email'), 'contact_points', ['email'], unique=False)
    op.create_index(op.f('ix_contact_points_id'), 'contact_points', ['id'], unique=False)
    op.create_index(op.f('ix_contact_points_name'), 'contact_points', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_points_name'), table_name='contact_points')
    op.drop_index(op.f('ix_contact_points_id'), table_name='contact_points')
    op.drop_index(op.f('ix_contact_points_email'), table_name='contact_points')
    op.drop_table('contact_points')
    # ### end Alembic commands ###
