"""add_acronym_description_logo_to_organizations

Revision ID: a6967d4f07f7
Revises: 7defb5a236a8
Create Date: 2026-03-25 10:53:35.885174

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6967d4f07f7"
down_revision: Union[str, None] = "7defb5a236a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations", sa.Column("acronym", sa.String(length=20), nullable=True)
    )
    op.add_column("organizations", sa.Column("description", sa.Text(), nullable=True))
    op.add_column(
        "organizations", sa.Column("logo_url", sa.String(length=500), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organizations", "logo_url")
    op.drop_column("organizations", "description")
    op.drop_column("organizations", "acronym")
    # ### end Alembic commands ###
