"""create_service_table

Revision ID: c4082fedec30
Revises: 42deb3269108
Create Date: 2026-03-25 12:46:08.598039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4082fedec30'
down_revision: Union[str, None] = '42deb3269108'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('EM_APROVACAO', 'ATIVO', 'INATIVO', 'SUSPENSO', name='servicestatus'), nullable=True),
    sa.Column('life_cycle', sa.Enum('PROPOSTA', 'CANDIDATO', 'OPERACIONAL', 'LEGADO', 'RETIRADO', name='servicelifecycle'), nullable=True),
    sa.Column('tipo', sa.Enum('REST', 'SOAP', 'FTP', 'AMHS', 'OUTRO', name='servicetipo'), nullable=True),
    sa.Column('publish_status', sa.Enum('PUBLICADO', 'RASCUNHO', 'INATIVO', name='servicepublishstatus'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_services_id'), 'services', ['id'], unique=False)
    op.create_index(op.f('ix_services_name'), 'services', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_services_name'), table_name='services')
    op.drop_index(op.f('ix_services_id'), table_name='services')
    op.drop_table('services')
    # ### end Alembic commands ###
