version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: swim_postgres
    environment:
      POSTGRES_USER: swim_user
      POSTGRES_PASSWORD: swim_password
      POSTGRES_DB: swim_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U swim_user -d swim_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  db_test:
    image: postgres:16-alpine
    container_name: swim_postgres_test
    environment:
      POSTGRES_USER: swim_user
      POSTGRES_PASSWORD: swim_password
      POSTGRES_DB: swim_test_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U swim_user -d swim_test_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: swim_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@swim.local
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  postgres_data:
